### PR TITLE
Added Avatar and Updated Help

### PR DESCRIPTION
**Pull request by TheEmperor342**

### CODE REVIEW

**Comment by itsmebirdie** [comment]
PR aknowledged. Review in progress

**Review by itsmebirdie — CHANGES_REQUESTED** [review]
Just one recommendation,
Add a separate help section for misc commands i.e, as we already have separate sections for moderation and fun, accessible by `>help {section}`.
Just wanted to have misc commands also in section as we don't want to complicate the help embed and we need it compact, so, just need you to do this we are ready to merge!

**Comment by itsmebirdie** [comment]
Commit acknowledged, review will b delayed.

**Review by itsmebirdie — COMMENTED** [review]
Commit testing failed, going to the next commit.

**Review by itsmebirdie — CHANGES_REQUESTED** [review]
Testing, failed.
cause: Critical Error Exception

exception:
```
IndentationError: unindent does not match any outer indentation level

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 52, in <module>
    bot.load_extension(F"Cogs.{i[:-3]}")  
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.Miscellaneous' raised an error: IndentationError: unindent does not match any outer indentation level (Miscellaneous.py, line 95)

```

Image for reference:
image

**Review by itsmebirdie — CHANGES_REQUESTED** [review]
Fixing spacing isn't the required change...


image

**Comment by TheEmperor342** [comment]
> Fixing spacing isn't the required change...
> 
> image

I believe the problem is with replit as its happened to me numerous times and if you still don't believe me, here is the proof:
[image](https://user-images.githubusercontent.com/83999665/120787275-cd733d00-c54c-11eb-86ca-ec2ce5b04e27.png)

**Comment by itsmebirdie** [comment]
Ok then, we will be testing this bot in a testing docker container

**Comment by itsmebirdie** [comment]
Approved

**Pull request merged**
