### PR TITLE
Added leveling system

### PR DESCRIPTION
**Pull request by PhantomKnight287**
image
 An example of rank card and that the bot is running flawlessly without any errors.

### CODE REVIEW

**Comment by itsmebirdie** [comment]
Even if it works in your server, we still need to test the stuff before merging...
Delayed review tomorrow.

**Comment by itsmebirdie** [comment]
This is the second time we are seeing tokens getting leaked publicly due to your non-consciousness, we don't expect this towards future commits, this shall be the last time we acknowledge these commits. 

P.S. Yes, we know that tokens get regenerated everytime a bot token gets leaked. But we still don't entertain leaking of bot tokens in commits.

**Review by itsmebirdie — CHANGES_REQUESTED** [review]
As expected, testing failed

Reason: Critical Error Exception.

image


Actual error as plaintext:
```
gitpod /workspace/discord-assistant $ python3 main.py
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.10/lib/python3.8/site-packages/discord.py-1.7.3-py3.8.egg/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
AttributeError: 'zipimporter' object has no attribute 'exec_module'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 84, in <module>
    bot.load_extension('dislevel')
  File "/home/gitpod/.pyenv/versions/3.8.10/lib/python3.8/site-packages/discord.py-1.7.3-py3.8.egg/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/gitpod/.pyenv/versions/3.8.10/lib/python3.8/site-packages/discord.py-1.7.3-py3.8.egg/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'dislevel' raised an error: AttributeError: 'zipimporter' object has no attribute 'exec_module'
```

**Comment by itsmebirdie** [comment]
Review shall be continued after the potential errors are fixed.

**Comment by itsmebirdie** [comment]
Ready for a re-review as it was acknowledged that it worked on development PC on a local environment.

**Comment by ujjwal-kr** [comment]
are you guys deciding to make some unit/integration tests for the project in the near future? That will cut off lot of review time imo. cc @itsmebirdie @PhantomKnight287

**Comment by itsmebirdie** [comment]
> are you guys deciding to make some unit/integration tests for the project in the near future? That will cut off lot of review time imo. cc @itsmebirdie @PhantomKnight287 

@ujjwal-kr we already have Assistant Testing Bot as in Hack Armour Testing and Misc server for unit and integrations tests both.

**Comment by itsmebirdie** [comment]
also, we aren't deciding to write those unit tests for now. We are still looking and learning for about how do we do it :D

**Comment by ujjwal-kr** [comment]
> > are you guys deciding to make some unit/integration tests for the project in the near future? That will cut off lot of review time imo. cc @itsmebirdie @PhantomKnight287
> 
> @ujjwal-kr we already have Assistant Testing Bot as in Hack Armour Testing and Misc server for unit and integrations tests both.

I get it but for some errors like this https://github.com/hackarmour/discord-assistant/pull/36#pullrequestreview-685075917
in the console, a little test with GitHub actions could be put to save review time. this is not what I'm expecting now but i encourage the fact that your team will learn that process cuz it saves lot of time and avoids critical mistakes!

**Comment by itsmebirdie** [comment]
> > > are you guys deciding to make some unit/integration tests for the project in the near future? That will cut off lot of review time imo. cc @itsmebirdie @PhantomKnight287
> > 
> > @ujjwal-kr we already have Assistant Testing Bot as in Hack Armour Testing and Misc server for unit and integrations tests both.
> 
> I get it but for some errors like this https://github.com/hackarmour/discord-assistant/pull/36#pullrequestreview-685075917
> in the console, a little test with GitHub actions could be put to save review time. this is not what I'm expecting now but i encourage the fact that your team will learn that process cuz it saves lot of time and avoids critical mistakes!

@ujjwal-kr I understand the importance of unit tests and automating is the easiest way to do that with some manual help, but we are still learning about the whole thing. We would be very thankful if you help us with these type of stuff!

**Comment by itsmebirdie** [comment]
Closing the Pull Request as no new commits  were observed within 5 days of commit request. Feel free to open it anytime.

**Comment by ujjwal-kr** [comment]
> > > > are you guys deciding to make some unit/integration tests for the project in the near future? That will cut off lot of review time imo. cc @itsmebirdie @PhantomKnight287
> > > 
> > > 
> > > @ujjwal-kr we already have Assistant Testing Bot as in Hack Armour Testing and Misc server for unit and integrations tests both.
> > 
> > 
> > I get it but for some errors like this [#36 (review)](https://github.com/hackarmour/discord-assistant/pull/36#pullrequestreview-685075917)
> > in the console, a little test with GitHub actions could be put to save review time. this is not what I'm expecting now but i encourage the fact that your team will learn that process cuz it saves lot of time and avoids critical mistakes!
> 
> @ujjwal-kr I understand the importance of unit tests and automating is the easiest way to do that with some manual help, but we are still learning about the whole thing. We would be very thankful if you help us with these type of stuff!

Sure! I will help you with some basic integration testing on the bot soon, it's kinda important for a cybersec org to have written atleast one test for their product.

**Pull request closed without merging**
