### PR TITLE
Add Music commands

### PR DESCRIPTION
**Pull request by Hrithik326**
Added a music cog to the cogs folder.

### CODE REVIEW

**Comment by ujjwal-kr** [comment]
thanks for the PR! I loved the fact that you commented about how the code works (which has not even been done in rest of the project yet 🙂) I hope you tested it well and it passes the review. 
Review acknowledged. CC @itsmebirdie

**Comment by Hrithik326** [comment]
Thank You

**Comment by itsmebirdie** [comment]
We are sorry for a delayed testing.
PR acknowledged for further testing and review.

**Review by itsmebirdie — COMMENTED** [review]
image

**Comment by Hrithik326** [comment]
"ffmpeg was not found" message shows up because you have to download FFmpeg.
Link to download: https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z

**Comment by itsmebirdie** [comment]
@Hrithik326 
image

Error as plaintext
```
gitpod /workspace/discord-assistant $ pip install ffmpeg-python
Requirement already satisfied: ffmpeg-python in /home/gitpod/.pyenv/versions/3.8.10/lib/python3.8/site-packages/ffmpeg_python-0.2.0-py3.8.egg (0.2.0)
Requirement already satisfied: future in /home/gitpod/.pyenv/versions/3.8.10/lib/python3.8/site-packages/future-0.18.2-py3.8.egg (from ffmpeg-python) (0.18.2)
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/home/gitpod/.pyenv/versions/3.8.10/bin/python3.8 -m pip install --upgrade pip' command.
gitpod /workspace/discord-assistant $ python3 main.py
The Bot is Ready
[download] Downloading playlist: rap god
[youtube:search] query "rap god": Downloading page 1
[youtube:search] playlist rap god: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] XbGs_qK2PQA: Downloading webpage
[youtube] Downloading just video XbGs_qK2PQA because of --no-playlist
[download] Finished downloading playlist: rap god


ffmpeg was not found.
gitpod /workspace/discord-assistant $ 
```


Kindly look onto this :D

**Comment by Hrithik326** [comment]
@itsmebirdie It won't work with the python module, you have to download it from the link mentioned above.

**Comment by itsmebirdie** [comment]
> @itsmebirdie It won't work with the python module, you have to download it from the link mentioned above.

This is a very lengthy process I see.

**Comment by itsmebirdie** [comment]
Review failed,
Reason(s): Fixed critical error exception with too much manual process, can't be automated. Requesting the author to find a new method for implementing the feature.

**Pull request closed without merging**
