### PR TITLE
Update the comments

### PR DESCRIPTION
**Pull request by mrnightdev**
Update comments for `main.py`, `TicTacToe.py`, `Welcomer.py` and `moderation.py`.

### CODE REVIEW

**Comment by 0xGamer** [comment]
PR  reviewed, assigning @itsmebirdie for testing.

**Comment by itsmebirdie** [comment]
Acknowledged for review.

**Review by itsmebirdie — COMMENTED** [review]
Would have really saved us some time if you just committed with the message that you reverted the old Tic Tac Toe module as per the latest update mentioned in #51 by @TheEmperor342 .

Also, requesting @0xGamer to please check the whole code for checking reversion of updates especially the revamps 😀.

**Comment by TheEmperor342** [comment]
> Would have really saved us some time if you just committed with the message that you reverted the old Tic Tac Toe module as per the latest update mentioned in #51 by @TheEmperor342 .
> 
> Also, requesting @0xGamer to please check the whole code for checking reversion of updates especially the revamps 😀.
I didn't Revert Tic Tac Toe What do you mean?

**Comment by itsmebirdie** [comment]
> > Would have really saved us some time if you just committed with the message that you reverted the old Tic Tac Toe module as per the latest update mentioned in #51 by @TheEmperor342 .
> > Also, requesting @0xGamer to please check the whole code for checking reversion of updates especially the revamps 😀.
> > I didn't Revert Tic Tac Toe What do you mean?

Hello again, 
Actually a PR confirming a revamp of the TTT module was created by @TheEmperor342 in #51 .
And you committed the changes without actually pulling the latest code. Git would automatically return error in these cases but I am not sure what exactly happened at your end :D

**Pull request closed without merging**
