### PR TITLE
Bugs fixed

### PR DESCRIPTION
**Pull request by TheEmperor342**

### CODE REVIEW

**Comment by ujjwal-kr** [comment]
good job, try to be a little descriptive with the pr from next time so the reviewer dont have to check the code and figure out what's been fixed

**Comment by itsmebirdie** [comment]
Aknowledged and requesting @0xGamer for review and testing.

**Comment by 0xGamer** [comment]
**Please don't be unprofessional with replies.**

**Comment by TheEmperor342** [comment]
> 
> 
> **Please don't be unprofessional with replies.**

Well this is fun module and there needs to be **some** unprofessional things here

After all this is a discord bot

**Comment by 0xGamer** [comment]
Doesn't matter it's a fun module. Again you have added "F for you lol" in your latest commit. Just send out the reason or don't send anything at all. I am sure you don't see replies like these on major bots.

**Comment by itsmebirdie** [comment]
Testing maybe delayed

**Review by itsmebirdie — APPROVED** [review]
Testing successful
PR Approved.

prf:
image
image
image
image
image
image

**Pull request merged**
