### PR TITLE
Potential fix for uptime

### PR DESCRIPTION
**Pull request by 0xGamer**

### CODE REVIEW

**Comment by 0xGamer** [comment]
Assigning @itsmebirdie for testing.

**Comment by itsmebirdie** [comment]
PR aknowledged.

**Review by itsmebirdie — COMMENTED** [review]
Code reviewed, Testing in progress

**Review by itsmebirdie — COMMENTED** [review]
Review in progress

**Review by itsmebirdie — COMMENTED** [review]
Fixes required


image

**Comment by itsmebirdie** [comment]
acknowledged.

**Review by itsmebirdie — CHANGES_REQUESTED** [review]
Review failed, 
Cause: Critical error



image



Potential Fixes required.

**Comment by itsmebirdie** [comment]
This PR will be closed if no new commits are seen in the next 42 hours.

**Comment by itsmebirdie** [comment]
Closing PR as no new commits were seen in the 42 hour time limit. Feel free to open it anytime.

**Comment by itsmebirdie** [comment]
Closing PR as no new commits were seen in the 42 hour time limit. Feel free to open it anytime.

**Pull request closed without merging**
