### PR TITLE
Added a linter

### PR DESCRIPTION
**Pull request by ujjwal-kr**
Added linter to check for code errors and code quality during code pushes and pull requests, all errors need not to be satisfy before merging but it's better to know them and fix the possible errors

### CODE REVIEW

**Comment by ujjwal-kr** [comment]
I'm acknowledging, reviewing, approving my own pr

**Comment by itsmebirdie** [comment]
That action wasn't legal but understandable.

**Comment by 0xGamer** [comment]
> That action wasn't legal but understandable.

He saved us from getting brain damage

**Comment by itsmebirdie** [comment]
> > That action wasn't legal but understandable.
> 
> He saved us from getting brain damage

Understandable....

**Comment by ujjwal-kr** [comment]
> That action wasn't legal but understandable.

I did that cuz I think you have not reviewed such kind of requests before and I had tested it, i have done some successful suicide attempts so let me deal with this shit
this-is-fine-its-fine

**Pull request merged**
